name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Setup Gradle
      run: |
        # ติดตั้ง Gradle โดยตรง
        sudo apt-get update
        sudo apt-get install -y gradle
        
        # หรือดาวน์โหลด version ที่ต้องการ
        wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
        sudo unzip -q gradle-8.5-bin.zip -d /opt/
        sudo ln -sf /opt/gradle-8.5/bin/gradle /usr/local/bin/gradle
        
        # ตรวจสอบ version
        gradle --version
        
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
    - name: Make Gradle executable and build
      run: |
        # ถ้ามี gradlew ให้ใช้
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew clean build --stacktrace
        else
          # ใช้ gradle โดยตรง
          gradle clean build --stacktrace
        fi
        
    - name: Build Debug APK
      run: |
        if [ -f "gradlew" ]; then
          ./gradlew assembleDebug --stacktrace
        else
          gradle assembleDebug --stacktrace
        fi
        
    - name: Find APK files
      run: |
        echo "🔍 Searching for APK files..."
        find . -name "*.apk" -type f
        
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: android-apks
        path: |
          **/*.apk
        retention-days: 30
        
    - name: Upload specific APK (if found)
      uses: actions/upload-artifact@v4
      if: hashFiles('**/debug/*.apk') != ''
      with:
        name: debug-apk
        path: '**/debug/*.apk'
        retention-days: 30
