name: Build GPS Tracker APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build Debug APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug --stacktrace --info
        
    - name: List build outputs
      run: |
        echo "🔍 Looking for APK files..."
        find . -name "*.apk" -type f
        ls -la app/build/outputs/apk/debug/ || echo "Debug output directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gps-tracker-apk
        path: |
          app/build/outputs/apk/debug/*.apk
          **/*.apk
        retention-days: 30
        if-no-files-found: warn
